# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/zenif/Documents/TP/Projet 1A/Projet 1A.cache/wt} [current_project]
set_property parent.project_path {D:/zenif/Documents/TP/Projet 1A/Projet 1A.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/zenif/Documents/TP/Projet 1A/Projet 1A.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Tick_1ms.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Lecture_code.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Assemble_Code.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Verif_Code.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Cmpt0to3.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/MUX4x4v1x4.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Disp1Digit.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Disp1of4Digits.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Disp4D.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Digicode.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/gestionAlarme.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Timer_30s.vhd}
  {D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/sources_1/new/Alarme.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/constrs_1/new/Alarme_Basys3.xdc}}
set_property used_in_implementation false [get_files {{D:/zenif/Documents/TP/Projet 1A/Projet 1A.srcs/constrs_1/new/Alarme_Basys3.xdc}}]


synth_design -top Alarme -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Alarme.dcp

catch { report_utilization -file Alarme_utilization_synth.rpt -pb Alarme_utilization_synth.pb }
